#define M_CORE_GBA 1
#define DISABLE_THREADING 1
#define MGBA_STANDALONE 1
#define HAVE_STRDUP 1
#define HAVE_STRNDUP 1
#define HAVE_STRLCPY 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LOCALE 1
#define HAVE_STRTOF_L 1
#define HAVE_SNPRINTF_L 1
#define HAVE_SETLOCALE 1
#define HAVE_XLOCALE 1
#define BUILD_STATIC 1

#define N3DS_VFS_H 1
#define N3DS_THREADING_H 1
#define POSIX_THREADING_H 1
#define SCE_VFS_H 1
#define SCE_THREADING_H 1
#define SWITCH_THREADING_H 1
#define __GETOPT_H__ 1
#define WINDOWS_THREADING_H 1
/* Copyright (c) 2013-2022 Jeffrey Pfau
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#ifndef M_SCRIPT_SOCKET_H
#define M_SCRIPT_SOCKET_H

enum mSocketErrorCode {
	mSCRIPT_SOCKERR_UNKNOWN_ERROR = -1,
	mSCRIPT_SOCKERR_OK = 0,
	mSCRIPT_SOCKERR_AGAIN,
	mSCRIPT_SOCKERR_ADDRESS_IN_USE,
	mSCRIPT_SOCKERR_CONNECTION_REFUSED,
	mSCRIPT_SOCKERR_DENIED,
	mSCRIPT_SOCKERR_FAILED,
	mSCRIPT_SOCKERR_NETWORK_UNREACHABLE,
	mSCRIPT_SOCKERR_NOT_FOUND,
	mSCRIPT_SOCKERR_NO_DATA,
	mSCRIPT_SOCKERR_OUT_OF_MEMORY,
	mSCRIPT_SOCKERR_TIMEOUT,
	mSCRIPT_SOCKERR_UNSUPPORTED,
};

#endif
